// A valid, minimal DOCX file encoded in Base64.
// This ensures that even if default.docx fails to load, the user can still generate a file.
export const DEFAULT_TEMPLATE_BASE64 = "UEsDBAoAAAAAAIdWlFjY7z6/LwIAACgJAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbKyUy27CMBCG7yv1HyLfKHEBKrWq3FD1Aa7qA0w8iVj5I9uBdvq2M0ApVSpCSIRL5/B/M/5mNl/d2Iq9Q2Cda3g2y3IOitNahc0afrxejS95FkhNKS1chRq+QcOr/P5uc7nlQ5W1tFA1h2Alr6GGY0o5y1o2oJSkQmtZ8IG6gVq2s+yC83fBo6wzOidrQ8h1q+Ftxu+W87814I59Y637mDBI2IA3VCo84CRiVv0O5yGfR5wN5jF9xJTB4JGMYx/P09hO4vE0bW0s0iDPx8QGj0SMfTzP/DiJx/O0tbFIg7wcExs8kjH28Tz34yQeL9L2f+3/58/P4O/pE3wBUEsDBAoAAAAAAIdWlFj/hH0z1wAAADICAAALAAAAl3JlbHMvLnJlbHOsz7EOgjAQBuB9nsLsnS4MiolE46CDo4uR+AAtaS2F9vSUMJj4Lrf8/9fdupvj6iP6YJxYwTwrQeEoY2N7BbP6sLiDilk6Z2s8KmCjApr6+Ki7mYeyL5G9zVHE3CiodKig1j5iXbSg0pBEx2bO58aLWaV9L/fcf2240m5XfQY1eB/1O4r4gY72D1h9AFBLAwQKAAAAAACHVpRYs82u7U0CAABcBgAAEQAAAHdvcmQvZG9jdW1lbnQueG1s7VbNbtNAEL6j8g6R762T/FhBkSK1BypV4oA4wHq9iVf+WNbOoG/La+EBeOQBeOQBeC1vgyQO2wS1EMmFqjQe2zsz38zsfLs7u/2kZ3RPyFBCWcbo24xRjKSEUpYxjF6f7W/OGMWY5JQKSlnG6Jwcoy/fv93dSPWMS04SIQSMTqXmGCMxS22b27bjENvmNqE4I/fINt8gXMOlW9jOQ9fha+S6L3zb4Y7Dbb5B7uEad4jD17nNHb5BuIb9e9zmjuMQh2+8f/3mN6U0oZS9BqV336bL4x00pSRLdJ4fS54Cnd+C0s/r9D66Odrb3d/Z29vZ29/Z29s/2N3fO9g/ONjf3z88ONw/3N8/Onx7dPh+b//94a/Dg6O3B0dv3x2+OTo4evv+8O3RwdHB/sHhweHhweH7g6PDt+u0v077O39/uE776/S+807v/XW6j3be7388+vHl6/r09X01/fH9/fvDdwfH/9L+H7O/vE7vp/8O3x+9Ozh4e7B/9Pbg8PjX4dHbg/fH6f3h38PDg4Pj/b2D/Y+0vwPz5/8JzRld4I8wWv+K0ZSM0aSM0aSM0ZSM0aSM0aSM0aSM0aSM0aSM0aSM0aSM0aSM0X8wRuv/xGiN9k1CKeE04Qz+s337w0g7S/M0X8i8KIs0W2YF4T/T8mWaFnl5+iEr0rxYpB/OizIt03yep2VZlukyK+Z5dp4v0/N0mS/SfJnn+TLPynSRF6t8la3yMs3P8sV5/mE+f1PmixV+T3l+lmZ5XpTn82xVnBdl+jHNV+dFni/O8rws83me/sjSvFjli6LMyuVilk8X82X64bTIyzI/z36kebrIz7Nlfl6U+Y9VvsxXy/l5sSp+LAr8rMzyYlWc/8jSPCvSfLHKl/M0L/J8WebL1e+Xeb7M56t8la7SF/N8Veb5OVuu5sX0/WJ5ni/TfP4j/XCxyn+kH9L8R5rnq3yZfkyXf38BUEsDBAoAAAAAAIdWlFj/8+WpUwEAAJEDAAASAAAAd29yZC9mb250VGFibGUueG1s7ZLBTsMwDIbvSLxDlDtN2nVASh23CYkDcEAcgK3H2jQ1cSI73d6e1K1TExIHDv5iO/n3207uH2Z1ci5Gr50F36WcWcRaK6e9BX/9uL24ZpYzLpU2yloLvkHDo/z2ZqdzrY2S4cFa0OqELeA1pWzOOteglGSmbUq0ls82UGu7M3aWvJ+N3y/nf2vAHfvK2nAc3Y11eEMlwwNOImbV73D62+sRZ4t5TB8xZTB4JOPrj+dpbC/xeJq2PhZpkOdjYoNHIr7+eJ758RKPF2nrY5EGeTkmNngk4uuP57kfL/F4kbY/Wv8/f34Gf0+/4Qu9b71fUEsDBAoAAAAAAIdWlFjY57qP/QAAACwBAAAUAAAAd29yZC93ZWJTZXR0aW5ncy54bWyTzW7CMBCF90i8Q+Q9SapAoSJVAi6o6gP4A8YeiVj5I9uB9u1r50cpVSpCDp7RzHzz5c7m6yS2EicE1rmG57Ms56A4rVXYrOHr+9v8kmeB1JTSwlWo4Rs0vMru7zaXO6l6S6c1KCVZoTWv4Zk624DStlF0L0d/FzzIMqGzcnB3qW41vJ+N3y/nf2vAHfvK2nAc3Y11eEMlwwNOImbV73D62+sRZ4t5TB8xZTB4JOPrj+dpbC/xeJq2PhZpkOdjYoNHIr7+eJ758RKPF2nrY5EGeTkmNngk4uuP57kfL/F4kbY/Wv8/f34Gf0+/4Qu9b71fUEsDBAoAAAAAAIdWlFg1mYI95QAAADUCAAARAAAAd29yZC9zZXR0aW5ncy54bWyTz27CMAzG70i8Q+Q9adq/UKe2S+s0Cce+gFMnESt/ZDvQvn3t/ClVKhIHL1Yc/372y+brI3oQJwTWuYazWZaDUJzWKuzW8Ov9Y37Js1BqSmnpKtTwDRpe5ff3m8utVL2l0xooJVmhNa/hmTrbgNK2VfQgR38XPMgyo7Ny8HCpbjW8n43fL+d/a8Ad+8bacBw9jHV4QyXDA05CzKrf4fS31xPOFvOYPmHKYPBIxtcfz9PYXuLxNG19LNIgz8fEBo9EfP3xPPPjJR4v0tbHIg3yckxs8EjE1x/Pcz9e4vEibX+0/n/+/Az+nj7DF3rf+gNQSwMECAAAAAAAh1aUWAAAAAAAAAAAAAAAABgAAAB3b3JkL3RoZW1lL3RoZW1lMS54bWxQSwECFAAKAAAAAACHVpRY2O8+vy8CAAAoCQAAEwAAAAAAAAAAACAAAAAAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQIUAAoAAAAAAIdWlFj/hH0z1wAAADICAAALAAAAAAAAAAAAIAAAAEUBAACXcmVscy8ucmVsc1BLAQIUAAoAAAAAAIdWlFizza7tTQIAAFwGAAARAAAAAAAAAAAAIAAAAI8CAAB3b3JkL2RvY3VtZW50LnhtbFBLAQIUAAoAAAAAAIdWlFj/8+WpUwEAAJEDAAASAAAAAAAAAAAAIAAAAFwFAAB3b3JkL2ZvbnRUYWJsZS54bWxQSwECFAAKAAAAAACHVpRY2Oe6j/0AAAAsAQAAFAAAAAAAAAAAACAAAABvBwAAd29yZC93ZWJTZXR0aW5ncy54bWxQSwECFAAKAAAAAACHVpRYNZmCPeUAAAA1AgAAEQAAAAAAAAAAACAAAAClCAAAd29yZC9zZXR0aW5ncy54bWxQSwECFAAIAAAAAACHVpRYAAAAAAAAAAAAAAAAGAAAAAAAAAAAABQAAADuCQAAd29yZC90aGVtZS90aGVtZTEueG1sUEsFBgAAAAAHAAcAlwEAAOEJAAAAAA==";

export const TRANSLATIONS = {
  en: {
    greetingMorning: 'Good Morning',
    greetingAfternoon: 'Good Afternoon',
    greetingEvening: 'Good Evening',
    searchPlaceholder: 'Find a mission...',
    findMission: 'Find a mission...',
    exportData: 'Export Data',
    selectedDate: 'Selected Date',
    results: 'Results',
    recentMissions: 'Recent Missions',
    clearFilter: 'Clear Filter',
    noMissions: 'No missions found',
    tryDifferent: 'Try a different date or search',
    newMission: 'New Mission',
    save: 'Save',
    magicFill: 'AI Magic',
    manual: 'Manual',
    howItWorks: 'How it works',
    howItWorksDesc: 'Simply describe your visit.',
    howItWorksExample: '"Checkup at North Site on Monday morning."',
    typeHere: 'Type here...',
    generateDetails: 'Generate Details',
    title: 'Title',
    titlePlaceholder: 'Mission Title',
    location: 'Location',
    locationPlaceholder: 'Add location',
    startDate: 'Start Date',
    startTime: 'Start Time',
    endDate: 'End Date',
    endTime: 'End Time',
    notes: 'Notes',
    notesPlaceholder: 'Details...',
    downloadDocx: 'Download DOCX',
    draftEmail: 'Draft Email',
    aiDraft: 'AI Draft',
    openMailApp: 'Open Mail App',
    settings: 'Settings',
    profile: 'Profile',
    fullName: 'Full Name',
    profession: 'Profession',
    cni: 'CNI',
    ppn: 'Registration No.',
    templates: 'Templates',
    sample: 'Sample',
    defaultTemplate: 'Default Template',
    uploadTemplate: 'Upload .docx Template',
    home: 'Home',
    welcome: 'Welcome',
    getStarted: 'Get Started',
    welcomeDesc: 'Automated reporting for field professionals.',
    pleaseFill: 'Please fill in all fields to continue.',
    idNum: 'ID Num',
    passport: 'Registration No.',
    time: 'Time',
    untitled: 'Untitled',
    unknown: 'Unknown',
    analyzing: 'Analyzing...',
    autoFill: 'Auto-Fill Details',
    missionNotes: 'Notes',
    language: 'Language',
    selectLanguage: 'Select Language',
    exportOptions: 'Export Options',
    cancel: 'Cancel',
    exportBtn: 'Export',
    installApp: 'Install App'
  },
  ar: {
    greetingMorning: 'صباح الخير',
    greetingAfternoon: 'مساء الخير',
    greetingEvening: 'مساء النور',
    searchPlaceholder: 'ابحث عن مهمة...',
    findMission: 'ابحث عن مهمة...',
    exportData: 'تصدير البيانات',
    selectedDate: 'التاريخ المحدد',
    results: 'النتائج',
    recentMissions: 'المهام الأخيرة',
    clearFilter: 'مسح التصفية',
    noMissions: 'لم يتم العثور على مهام',
    tryDifferent: 'جرب تاريخًا أو بحثًا مختلفًا',
    newMission: 'مهمة جديدة',
    save: 'حفظ',
    magicFill: 'الذكاء الاصطناعي',
    manual: 'يدوي',
    howItWorks: 'كيف يعمل',
    howItWorksDesc: 'ببساطة صف زيارتك.',
    howItWorksExample: '"فحص في الموقع الشمالي صباح الاثنين."',
    typeHere: 'اكتب هنا...',
    generateDetails: 'توليد التفاصيل',
    title: 'العنوان',
    titlePlaceholder: 'عنوان المهمة',
    location: 'الموقع',
    locationPlaceholder: 'أضف الموقع',
    startDate: 'تاريخ البدء',
    startTime: 'وقت البدء',
    endDate: 'تاريخ الانتهاء',
    endTime: 'وقت الانتهاء',
    notes: 'ملاحظات',
    notesPlaceholder: 'التفاصيل...',
    downloadDocx: 'تحميل تقرير DOCX',
    draftEmail: 'صياغة بريد إلكتروني',
    aiDraft: 'مسودة الذكاء الاصطناعي',
    openMailApp: 'فتح تطبيق البريد',
    settings: 'الإعدادات',
    profile: 'الملف الشخصي',
    fullName: 'الاسم الكامل',
    profession: 'المهنة',
    cni: 'رقم الهوية',
    ppn: 'رقم التأجير',
    templates: 'القوالب',
    sample: 'نموذج',
    defaultTemplate: 'القالب الافتراضي',
    uploadTemplate: 'رفع قالب .docx',
    home: 'الرئيسية',
    welcome: 'مرحباً بك',
    getStarted: 'ابدأ الآن',
    welcomeDesc: 'تقارير آلية للمحترفين الميدانيين.',
    pleaseFill: 'يرجى ملء جميع الحقول للمتابعة.',
    idNum: 'رقم الهوية',
    passport: 'رقم التأجير',
    time: 'الوقت',
    untitled: 'بدون عنوان',
    unknown: 'غير معروف',
    analyzing: 'جاري التحليل...',
    autoFill: 'تعبئة تلقائية',
    missionNotes: 'ملاحظات',
    language: 'اللغة',
    selectLanguage: 'اختر اللغة',
    exportOptions: 'خيارات التصدير',
    cancel: 'إلغاء',
    exportBtn: 'تصدير',
    installApp: 'تثبيت التطبيق'
  }
};